=== ejetzer/Cassiopee/parsing/source.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT html (head, body)>
    <!ELEMENT head (title, meta*)>
        <!ELEMENT title #PCDATA>
        <!ELEMENT meta EMPTY>
            <!ATTLIST meta  http-equiv CDATA
                            content CDATA
                            charset CDATA>
    <!ENTITY % block_content "((#PCDATA|div|p|img|section)*)">
    <!ELEMENT body (%block_content;)>
        <!ELEMENT div ANY>
        <!ELEMENT p ANY>
        <!ELEMENT img EMPTY>
            <!ATTLIST img   src CDATA
                            alt CDATA
                            title CDATA>
        <!ELEMENT section ANY>

=== ejetzer/Cassiopee/source.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- This is a comment -->
<!DOCTYPE html SYSTEM "./source.dtd" [
    <!ELEMENT title #PCDATA>
    <!ATTLIST title lang CDATA>
    <!ENTITY content "This is some textual content. I am impressed by the fact that this is actual writing, encoded on a computer in the form of binary numbers &amp; eventually as electrical currents.">
]>
<html>
    <head>
        <title>Page web</title>
        <meta http-equiv="Content-Type" content="text/html" charset="utf-8"/>
    </head>
    <body>
        <section>This is some text.</section>
        <p>&content;</p>
        <p>This is some more textual content, there only to make a point. Do not forget, to be awesome &amp; to decrease worldsuck.</p>
        <img src="Stuff!"/>
        <p>Normally, the filters should pick up all three paragraphs.</p>
    </body>
</html>
